import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ThemeProvider from '~/components/molecules/theme-provider';
import Header from '~/components/organisms/layout/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
