import '../globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { locale as localeParam } from 'next/root-params';
import { NextIntlClientProvider } from 'next-intl';

import { ThemeProvider } from '~/components/molecules/theme-provider';
import { Toaster } from '~/components/ui/sonner';
import { TooltipProvider } from '~/components/ui/tooltip';
import { routing } from '~/i18n/routing';
import { cn } from '~/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const generateStaticParams = () => routing.locales.map(locale => ({ locale }));

const RootLayout = async ({ children }: LayoutProps<'/[locale]'>) => {
    const locale = await localeParam();

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={cn(inter.className, 'flex flex-col min-h-svh antialiased')}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Toaster richColors />
                    <TooltipProvider>
                        <NextIntlClientProvider>{children}</NextIntlClientProvider>
                    </TooltipProvider>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
