#!/bin/sh

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
bun lint-staged ||
  (
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
     Run bun lint, add changes and try commit again.
     '
    false
  )

echo '⌛️⌛️⌛️ You win this time... I am committing this now. ⌛️⌛️⌛️'
