#!/bin/sh

echo '🏗️👷 Running Biome on staged files before commit'

bun lint-staged ||
  (
    echo '🔨❌ Lint/format errors. Run `bun lint:fix` then re-stage. 🔨❌
     '
    false
  )

echo '✅ Staged files clean. Committing.'
